### ISSUE TITLE
Use cleaner Dockerfile base

### ISSUE THREAD

**Issue by bloodearnest** [opensafely-core/research-action#4]
We used cohortextractor as a base as it has docker installed already, mainly.

We could just use ubuntu:20.04, and install docker ourselves, perhaps.

We'd always want to install the latest opensafley tools each action run, but maybe we'd want to make specific research-action base image so that things are a) consistant and b) run a bit faster?

**Comment by bloodearnest** [comment]
I think it is worth optimising the runtime by having a base image, because it would reduce our actions minute budget consumption across all projects in OS.

**Comment by evansd** [comment]
Obviated by #9
